spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
logging.level.web=DEBUG
spring.messages.basename=messages,front-validation,back-validation,solr-search
server.servlet.context-path=/rabbit/api
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.servlet.multipart.max-file-size=20MB
server.port=9100

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
