spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
logging.level.web=DEBUG
spring.messages.basename=messages,front-validation,back-validation,solr-search
server.servlet.context-path=/rabbit/api
#spring.jackson.date-format=dd.MM.yyyy HH:mm:ss
spring.jackson.mapper.accept-case-insensitive-enums= true
spring.servlet.multipart.max-file-size=20MB
server.port=9100

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.email.name=email-notification-queue
rabbitmq.queue.sms.name=sms-notification-queue
rabbitmq.routing.email.name=email-notification-routing
rabbitmq.routing.sms.name=sms-notification-routing
rabbitmq.exchange.name=rabbit-conf-exchange
rabbitmq.queue.announcement.name=announcement-queue
rabbitmq.routing.announcement.name=announcement-routing
